/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stecgames.visão;

import java.sql.Connection;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import stecgames.modelo.Pedidos;
import stecgames.modelo.Requisicoes;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import stecgames.modelo.Produtos;
import stecgames.persistencia.ConnectionFactory;
import stecgames.persistencia.PedidoDAO;
import stecgames.persistencia.ProdutoDAO;
import stecgames.persistencia.RequisicaoDAO;
import static stecgames.visão.TelaPrincipal.JdpPrincipal;

/**
 *
 * @author sala308b
 */
public class telaListaPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaListaPedido
     */
    public telaListaPedido() {
        initComponents();
        
         DefaultTableModel modelo = (DefaultTableModel) jTPedido.getModel();
        
        readJTable();
    }
    
    
    public void  readJTable(){
        
         DefaultTableModel modelo = (DefaultTableModel) jTPedido.getModel();
         modelo.setNumRows(0);
         
          ArrayList<Pedidos> lista = null;
          
          
          SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
          NumberFormat nf = NumberFormat.getCurrencyInstance();
         
          try{
            lista = PedidoDAO.listar();
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Deu Ruim.");
        }
          
         
          
         for(Pedidos p:lista){
      
         modelo.addRow(new Object[]{
        
            p.getCodigoPedido(),
            p.getNomeProduto(),
            p.getMarcaProduto(),
            p.getQtdProduto(),
            nf.format(p.getValorProduto()),
            fmt.format(p.getDtPedido())
            
                 
     });
        
    }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTPedido = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btVoltarLista = new javax.swing.JButton();
        btVoltarTelaP = new javax.swing.JButton();
        btCancelarCompra = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);

        jTPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Marca", "Quantidade", "Valor Total", "Data do pedido"
            }
        ));
        jTPedido.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTPedido.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTPedido);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jButton1.setText("Gerar relatório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btVoltarLista.setText("Voltar para produtos");
        btVoltarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarListaActionPerformed(evt);
            }
        });

        btVoltarTelaP.setText("Tela principal");
        btVoltarTelaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarTelaPActionPerformed(evt);
            }
        });

        btCancelarCompra.setText("Cancelar compra");
        btCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btVoltarTelaP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btVoltarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btCancelarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVoltarTelaP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btCancelarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVoltarLista)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarListaActionPerformed
        telaListaProduto frame = new telaListaProduto();
        
        
        JdpPrincipal.add(frame);
        frame.setLocation(
        JdpPrincipal.getWidth()/2 - frame.getWidth()/2,
        JdpPrincipal.getHeight()/2 - frame.getHeight()/2);
        
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarListaActionPerformed

    private void btVoltarTelaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarTelaPActionPerformed
         
        dispose();
    }//GEN-LAST:event_btVoltarTelaPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con = ConnectionFactory.getConnection();
        String src = "RPedidos.jasper";
        JasperPrint jasperPrint = null;
        try {
            jasperPrint = JasperFillManager.fillReport(src, null, con);
        } catch (JRException ex) {
            System.out.println("Error: " + ex);
        }
        JasperViewer view = new JasperViewer(jasperPrint, false);
        view.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarCompraActionPerformed

        if (jTPedido.getSelectedRow() != -1) {

            Pedidos pe = new Pedidos();
            
            Produtos pr = new Produtos();
            
            Produtos pa = new Produtos();

            pe.setCodigoPedido((int) jTPedido.getValueAt(jTPedido.getSelectedRow(), 0));
            
           int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "Confirmação", JOptionPane.YES_NO_OPTION);
           
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    
                    
                   String pegarIdAux = jTPedido.getValueAt(jTPedido.getSelectedRow(), 0).toString();
                   int pegarID = Integer.parseInt(pegarIdAux);
               
                   pr = ProdutoDAO.buscarIdP(pegarID);
                    
                    pa.setNome(pr.getNome());
                    pa.setMarca(pr.getMarca());
                    pa.setQntEstoque(pr.getQntEstoque());
                    pa.setQntMinima(pr.getQntMinima());
                    pa.setUnidMedida(pr.getUnidMedida());
                    pa.setValorUnidade(pr.getValorUnidade());
                    pa.setTipo(pr.getTipo());
                    pa.setCodigo((int) pr.getCodigo());
                    pa.setNumPedido(0);
                    
                    PedidoDAO.excluir(pe);
                    ProdutoDAO.atualizar(pa);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(telaListaPedido.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(telaListaPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (resposta == JOptionPane.NO_OPTION) {
                return;
            }

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um pedido para cancelar.");
        }
    }//GEN-LAST:event_btCancelarCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarCompra;
    private javax.swing.JButton btVoltarLista;
    private javax.swing.JButton btVoltarTelaP;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTPedido;
    // End of variables declaration//GEN-END:variables
}
