/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stecgames.visão;

import java.sql.Connection;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import stecgames.modelo.TurmaCurso;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import stecgames.persistencia.ConnectionFactory;
import stecgames.persistencia.CursoDAO;
import stecgames.utilitarios.ApenasNumeros;
import stecgames.utilitarios.ApenasNumerosVirg;

/**
 *
 * @author Gustavo
 */
public class TelaTurmaCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaTurmaCurso
     */
    public TelaTurmaCurso() {
        initComponents();
        
        
        
        
        txtIdadeMinC.setDocument(new ApenasNumeros());
        txtIdadeMaxC.setDocument(new ApenasNumeros());
        txtValMatrC.setDocument(new ApenasNumerosVirg());
        txtValMensC.setDocument(new ApenasNumerosVirg());
        txtQtdParcelasC.setDocument(new ApenasNumeros());        
                
         
        DefaultTableModel modelo = (DefaultTableModel) jTCurso.getModel(); // tabela Jtable
        
        readJTable();
        
    }
    
     public void  readJTable(){
        
         DefaultTableModel modelo = (DefaultTableModel) jTCurso.getModel();
         modelo.setNumRows(0);
          ArrayList<TurmaCurso> lista = null;
          
         
         
          try{
            lista = CursoDAO.listar();
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Ocorreu um erro!");
        }
          
         for(TurmaCurso c:lista){
      
         modelo.addRow(new Object[]{
        
            c.getCod(),
            c.getNome(),
            c.getIdadeMin(),
            c.getIdadeMax(),
            c.getPeriodo(),
            c.getValorMat(),
            c.getValorMens(),
            c.getQtdParcelas(),
            c.getObservacao()
                 
     });
        
    }
         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCurso = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtValMensC = new javax.swing.JTextField();
        cbPeriodoC = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeC = new javax.swing.JTextField();
        txtIdadeMinC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtValMatrC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtObsC = new javax.swing.JTextField();
        txtIdadeMaxC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQtdParcelasC = new javax.swing.JTextField();

        jLabel3.setText("Nome:");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Controle de cadastro do Curso");

        jTCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Idade Min.", "Idade Max.", "Período", "Valor Mat.", "Valor Mens.", "Parcelas", "Obs."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCurso.setName(""); // NOI18N
        jTCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCursoMouseClicked(evt);
            }
        });
        jTCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTCursoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTCurso);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Gerar Relatorio");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(13, 13, 13)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setText("Valor da Matrícula:");

        cbPeriodoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Matutino", "Vespertino", "Noturno" }));

        jLabel2.setText("Idade Mínima:");

        jLabel8.setText("Parcelas:");

        jLabel4.setText("Idade Máxima:");

        txtNomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel9.setText("Observação:");

        jLabel7.setText("Valor Mensalidade:");

        jLabel5.setText("Período:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(txtIdadeMinC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdadeMaxC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbPeriodoC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtValMatrC)
                    .addComponent(txtValMensC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtQtdParcelasC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtObsC)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbPeriodoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtQtdParcelasC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdadeMinC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtValMatrC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtObsC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdadeMaxC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(txtValMensC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        dispose();  
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if (jTCurso.getSelectedRow() != -1) {

            TurmaCurso turmacurso = new TurmaCurso();

            turmacurso.setCod((int) jTCurso.getValueAt(jTCurso.getSelectedRow(), 0));
            
           int resposta = JOptionPane.showConfirmDialog(null, "Deseja excluir?", "Confirmação", JOptionPane.YES_NO_OPTION);
           
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    CursoDAO.excluir(turmacurso);
                    JOptionPane.showMessageDialog(null, "Excluido com sucesso!");
                } catch (SQLException ex) {
                    Logger.getLogger(TelaTurmaCurso.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TelaTurmaCurso.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (resposta == JOptionPane.NO_OPTION) {
                return;
            }
            
         /*

            txtNome.setText("");
            txtMarca.setText("");
            txtQtnEstoque.setText("");
            txtQntMinima.setText("");
            txtUnidMedida.setText("");
            txtValorUnidade.setText("");
            cbTipo.setSelectedItem("Selecione");
            */
            readJTable();
                                        
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");  //Duvida no excluir: tenho que fechar o programa pra que eu visualize que ele excluiu
        }
        
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtNomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        
        
         
       
        
          
         
        String nomeC;
        int IdadeMinC = 0;
        int IdadeMaxC = 0;            
        double ValMatrC = 0;
        double ValMensC = 0;
        int QtdParcelasC = 0;        
        String ObsC;
        String msgErro = "";
       
        
       
       
       nomeC = txtNomeC.getText();   
              
       //String PeriodoC = cbPeriodoC.getSelectedItem().toString();                 
        
       String IdadeMiCAux = txtIdadeMinC.getText();
       
       String IdadeMaCAux = txtIdadeMaxC.getText();
       
       String Periodo = cbPeriodoC.getSelectedItem().toString();      
        
       String ValMatCAux = txtValMatrC.getText();
       
       String ValMenSCAux = txtValMensC.getText();
       
       String QtdParcCAux = txtQtdParcelasC.getText();
       
       ObsC = txtObsC.getText();
       
       
       try {
       
       
       if (nomeC.equals("") && Periodo.equals("") && IdadeMiCAux.equals("")
                && IdadeMaCAux.equals("") && ValMatCAux.equals("")
                && ValMenSCAux.equals("") && QtdParcCAux.equals("")){
           
           
            msgErro = "TODOS OS CAMPOS DEVEM ESTAR PREENCHIDOS.";
            JOptionPane.showMessageDialog(null, msgErro);
        } else 
            if (nomeC.equals("")) {
                msgErro = "Preencha o campo NOME antes de continuar.";
                JOptionPane.showMessageDialog(null, msgErro);
            } else {
                if (IdadeMiCAux.equals("")) {
                    msgErro = "Preencha o campo Idade Minima antes de continuar.";
                    JOptionPane.showMessageDialog(null, msgErro);
                } else {
                    if (IdadeMaCAux.equals("")) {
                        msgErro = "Preencha o campo Idade Maxima antes de continuar.";
                        JOptionPane.showMessageDialog(null, msgErro);
                    } else {
                        if(Periodo.equals("Selecione")){
                          msgErro = "Selecione um Periodo antes de continuar.";
                           JOptionPane.showMessageDialog(null, msgErro);
                         }else{
                        if (ValMatCAux.equals("")) {
                            msgErro = "Preencha o campo Valor Matricula antes de continuar.";
                            JOptionPane.showMessageDialog(null, msgErro);
                        } else {
                            if (ValMenSCAux.equals("")) {
                                msgErro = "Preencha o campo Valor da Mensalidade antes de continuar.";
                                JOptionPane.showMessageDialog(null, msgErro);
                            } else {
                                if (QtdParcCAux.equals("")) {
                                    msgErro = "Preencha o campo Quantidade de Parcelas antes de continuar.";
                                    JOptionPane.showMessageDialog(null, msgErro);
                                } else {
                                    
                                        
                                      
                                          
                                    IdadeMinC = Integer.parseInt(IdadeMiCAux);
                                    IdadeMaxC = Integer.parseInt(IdadeMaCAux);                                    
                                   
                                    QtdParcelasC = Integer.parseInt(QtdParcCAux);
                                    
                                    
                                     String Mat = ValMatCAux.replace(",", ".");                                     
            
                                     double valorMat = Double.parseDouble(Mat);
                                     
                                     String Mens = ValMenSCAux.replace(",", ".");                                     
            
                                     double valorMens = Double.parseDouble(Mens);
                                     
                                     
                                     
                                     
         try {
        
        if (jTCurso.getSelectedRow() != -1) {

            TurmaCurso turmacurso = new TurmaCurso();
            
            
            String valorAux = txtValMatrC.getText();
            String valorAux2 = txtValMensC.getText();
            
            String aux = valorAux.replace(",", ".");
            String aux2 = valorAux2.replace(",", ".");
            
            double valor = Double.parseDouble(aux); 
            double valor2 = Double.parseDouble(aux2);
          
            
            turmacurso.setNome(txtNomeC.getText());            
            turmacurso.setIdadeMin(Integer.parseInt(txtIdadeMinC.getText()));            
            turmacurso.setIdadeMax(Integer.parseInt(txtIdadeMaxC.getText()));
            turmacurso.setPeriodo(cbPeriodoC.getSelectedItem().toString());         
            turmacurso.setValorMat(valor);         
            turmacurso.setValorMens(valor2);
            turmacurso.setQtdParcelas(Integer.parseInt(txtQtdParcelasC.getText()));
            turmacurso.setObservacao(txtObsC.getText()); 
            
            turmacurso.setCod((int) jTCurso.getValueAt(jTCurso.getSelectedRow(), 0));
            
          
            
         
         
         
         int resposta = JOptionPane.showConfirmDialog(null, "Deseja atualizar?", "Confirmação", JOptionPane.YES_NO_OPTION);
           
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    CursoDAO.atualizar(turmacurso);
                    JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");
                } catch (SQLException ex) {
                    Logger.getLogger(TelaTurmaCurso.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TelaTurmaCurso.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (resposta == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Nada foi atualizado!");
                return; 
            }
            
        
            readJTable();
                                        
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para atualizar.");  
        }
        
        } catch (Exception ex) {
           String msgErro1;
           msgErro1 = "Não é permitido campo nulo";
           JOptionPane.showMessageDialog(null, msgErro1);
       } 
        
        
        
                                }
                            }
                        }
                        }
                    }
                }
            }
       
        } catch (Exception ex) {
           String msgErro1;
           msgErro1 = "Insira apenas uma virgula";
           JOptionPane.showMessageDialog(null, msgErro1);
       }
       
       
       
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCursoMouseClicked
       
        if (jTCurso.getSelectedRow() != -1) {
            
           
              
            NumberFormat nf = new DecimalFormat("#.#");

            txtNomeC.setText(jTCurso.getValueAt(jTCurso.getSelectedRow(), 1).toString());
            txtIdadeMinC.setText(jTCurso.getValueAt(jTCurso.getSelectedRow(), 2).toString());
            txtIdadeMaxC.setText(jTCurso.getValueAt(jTCurso.getSelectedRow(), 3).toString());
            cbPeriodoC.setSelectedItem((jTCurso.getValueAt(jTCurso.getSelectedRow(), 4)));
            txtValMatrC.setText(nf.format(jTCurso.getValueAt(jTCurso.getSelectedRow(), 5)));
            txtValMensC.setText(nf.format(jTCurso.getValueAt(jTCurso.getSelectedRow(), 6)));
            txtQtdParcelasC.setText(jTCurso.getValueAt(jTCurso.getSelectedRow(), 7).toString());
            txtObsC.setText(jTCurso.getValueAt(jTCurso.getSelectedRow(), 8).toString());
            

        }
        
        
        
        
    }//GEN-LAST:event_jTCursoMouseClicked

    private void jTCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCursoKeyReleased
        
     if (jTCurso.getSelectedRow() != -1) {
            
            NumberFormat nf = new DecimalFormat("#.#");

            txtNomeC.setText(jTCurso.getValueAt(jTCurso.getSelectedRow(), 1).toString());
            txtIdadeMinC.setText(jTCurso.getValueAt(jTCurso.getSelectedRow(), 2).toString());
            txtIdadeMaxC.setText(jTCurso.getValueAt(jTCurso.getSelectedRow(), 3).toString());
            cbPeriodoC.setSelectedItem((jTCurso.getValueAt(jTCurso.getSelectedRow(), 4)));
            txtValMatrC.setText(nf.format(jTCurso.getValueAt(jTCurso.getSelectedRow(), 5)));
            txtValMensC.setText(nf.format(jTCurso.getValueAt(jTCurso.getSelectedRow(), 6)));
            txtQtdParcelasC.setText(jTCurso.getValueAt(jTCurso.getSelectedRow(), 7).toString());
            txtObsC.setText(jTCurso.getValueAt(jTCurso.getSelectedRow(), 8).toString());
            

        }
        
        
    }//GEN-LAST:event_jTCursoKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 /*try {                                        
            
            Connection con = ConexaoFactory.getConexao(); //conn = ConnectionFactory.getConnection();
            
            String src = "IREPORT/RelatorioDoCurso.jasper";
            
            JasperPrint jasperPrint = null;
            
            try {
                jasperPrint = JasperFillManager.fillReport(src, null, con);
            } catch (JRException ex) {
                System.out.println("Erro no Relatorio: " + ex);
            }
            
            JasperViewer view = new JasperViewer(jasperPrint, false);
            
            view.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaTurmaCurso.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaTurmaCurso.class.getName()).log(Level.SEVERE, null, ex);
        }   */
 
 Connection con = ConnectionFactory.getConnection();
        String src = "IREPORT/RelatorioDoCurso.jasper";
        JasperPrint jasperPrint = null;
        try {
            jasperPrint = JasperFillManager.fillReport(src, null, con);
        } catch (JRException ex) {
            System.out.println("Error: " + ex);
        }
        JasperViewer view = new JasperViewer(jasperPrint, false);
        view.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbPeriodoC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCurso;
    private javax.swing.JTextField txtIdadeMaxC;
    private javax.swing.JTextField txtIdadeMinC;
    private javax.swing.JTextField txtNomeC;
    private javax.swing.JTextField txtObsC;
    private javax.swing.JTextField txtQtdParcelasC;
    private javax.swing.JTextField txtValMatrC;
    private javax.swing.JTextField txtValMensC;
    // End of variables declaration//GEN-END:variables
}
