/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stecgames.visão;

import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import stecgames.modelo.Armarios;
import stecgames.modelo.Produtos;
import stecgames.persistencia.ArmarioDAO;
import stecgames.persistencia.ProdutoDAO;
import static stecgames.visão.TelaPrincipal.JdpPrincipal;

/**
 *
 * @author Daniel
 */
public class telaListaArmario extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaListaArmario
     */
    public telaListaArmario() {
        initComponents();
     
        DefaultTableModel modelo = (DefaultTableModel) jTArmario.getModel();
        
        readJTable();
    }
    
    public void  readJTable(){
        
         DefaultTableModel modelo = (DefaultTableModel) jTArmario.getModel();
         modelo.setNumRows(0);
         
         /*jTArmario.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                
                Armarios armario = new Armarios();
                
                //A coluna do status é 3
                Object ref = table.getValueAt(row, 3);//Coluna qnt estoque
                
                int refAux = Integer.parseInt(ref.toString());
                
                
                Object ref2 = table.getValueAt(row, 4);//Coluna qnt minima
                
                int ref2Aux = Integer.parseInt(ref2.toString());
                
                //Coloca cor em todas as linhas,COLUNA(3) que tem o valor menor que qnt minima
                if (ref != null && refAux < ref2Aux) {//Se qnt estoque for menor que qnt minima
                    setBackground(Color.RED);//Preenche a linha de vermelho
                    setForeground(Color.WHITE);//E a fonte de branco
                } else {
                    boolean sel = isSelected;
                    if (sel == true) {
                        setBackground(getBackground());
                        setForeground(getForeground());
                    } else {//Se qnt estoque não for menor que qnt minima
                        setBackground(Color.WHITE);//Preenche a linha de branco
                        setForeground(new Color(51, 51, 51));//E a fonte de preto
                         
                    }
                }
                return this;
            }
        });*/
         
         
          ArrayList<Armarios> lista = null;
          
          SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
          NumberFormat nf = NumberFormat.getCurrencyInstance();
         
          try{
            lista = ArmarioDAO.listar();
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Deu Ruim.");
        }
          
         for(Armarios p:lista){
      
         modelo.addRow(new Object[]{
        
            p.getCodArmario(),
            p.getQtdMaxima(),
            p.getQtdOcupada()
            
                 
     });
        
    }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTArmario = new javax.swing.JTable();
        btCadastrar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);

        jTArmario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Qnt. Máxima", "Qnt. Ocupada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTArmario.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTArmario);

        btCadastrar.setText("Cadastrar Armário");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btVoltar.setText("Sair");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btVoltar)
                        .addGap(85, 85, 85)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        telaCadastroArmario frame = new telaCadastroArmario();
        
        JdpPrincipal.add(frame);
        frame.setLocation(
        JdpPrincipal.getWidth()/2 - frame.getWidth()/2,
        JdpPrincipal.getHeight()/2 - frame.getHeight()/2);
        
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed

        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTArmario;
    // End of variables declaration//GEN-END:variables
}
