/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stecgames.visão;

import java.sql.Connection;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import stecgames.modelo.TurmaCurso;
import stecgames.modelo.TurmaTreinamento;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import stecgames.persistencia.ConnectionFactory;
import stecgames.persistencia.CursoDAO;
import stecgames.persistencia.TreinamentoDAO;
import stecgames.utilitarios.ApenasNumeros;
import stecgames.utilitarios.ApenasNumerosVirg;

/**
 *
 * @author Gustavo
 */
public class TelaTurmaTreinamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaTurmaTreinamento
     */
    public TelaTurmaTreinamento() {
        initComponents();
        
        
        
        txtCargaHorariaT.setDocument(new ApenasNumeros());
        txtValTreinamento.setDocument(new ApenasNumerosVirg());
        txtParcelasT.setDocument(new ApenasNumeros());
        
        DefaultTableModel modelo = (DefaultTableModel) jTreinamento.getModel(); // tabela Jtable
        
        readJTable();
        
    }
    
    public void  readJTable(){
        
         DefaultTableModel modelo = (DefaultTableModel) jTreinamento.getModel();
         modelo.setNumRows(0);
          ArrayList<TurmaTreinamento> lista = null;
          
         
         
          try{
            lista = TreinamentoDAO.listar();
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Ocorreu um erro!");
        }
          
         for(TurmaTreinamento c:lista){
      
         modelo.addRow(new Object[]{
        
            c.getCod(),
            c.getEmpresa(),
            c.getConteudo(),
            c.getCargaHoraria(),
            c.getDataInicio(),
            c.getDataTermino(),
            c.getValorTreinamento(),
            c.getParcelas(),
            c.getObservacao()
                 
     });
        
    }
         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDataIninioT = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreinamento = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtDataTerminoT = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtConteudoT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDataInicioT = new javax.swing.JFormattedTextField();
        txtObsT = new javax.swing.JTextField();
        txtCargaHorariaT = new javax.swing.JTextField();
        txtParcelasT = new javax.swing.JTextField();
        txtNomeT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValTreinamento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        try {
            txtDataIninioT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Controle de cadastro do Treinamento");

        jTreinamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Empresa", "Conteudo", "Carga Horaria", "Data Inicio", "Data Termino", "Valor Treinamento", "Parcelas", "Observacao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTreinamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreinamentoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTreinamentoMouseReleased(evt);
            }
        });
        jTreinamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTreinamentoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTreinamento);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Gerar Relatorio");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        try {
            txtDataTerminoT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Data início:");

        jLabel2.setText("Conteudo:");

        jLabel8.setText("Observação:");

        jLabel7.setText("Parcelas:");

        jLabel3.setText("Carga Horária:");

        try {
            txtDataInicioT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Data Termino:");

        txtValTreinamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.##"))));

        jLabel6.setText("Valor do Treinamento:");

        jLabel1.setText("Empresa:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCargaHorariaT, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtConteudoT))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtValTreinamento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataTerminoT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataInicioT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtParcelasT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtObsT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDataInicioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtParcelasT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtConteudoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDataTerminoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtObsT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCargaHorariaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtValTreinamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        dispose(); 
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       
        
        try {
        
        if (jTreinamento.getSelectedRow() != -1) {

            TurmaTreinamento turmatreinamento = new TurmaTreinamento();

            turmatreinamento.setCod((int) jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 0));
            
           int resposta = JOptionPane.showConfirmDialog(null, "Deseja excluir?", "Confirmação", JOptionPane.YES_NO_OPTION);
           
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    TreinamentoDAO.excluir(turmatreinamento);
                    JOptionPane.showMessageDialog(null, "Excluido com sucesso!");
                } catch (SQLException ex) {
                    Logger.getLogger(TelaTurmaTreinamento.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TelaTurmaTreinamento.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (resposta == JOptionPane.NO_OPTION) {
                return;
            }
            
         
            readJTable();
                                        
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");  //Duvida no excluir: tenho que fechar o programa pra que eu visualize que ele excluiu
        }
        
        
         } catch (Exception ex) {
           String msgErro1;
           msgErro1 = "Não é permitido campo nulo";
           JOptionPane.showMessageDialog(null, msgErro1);
       } 
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    String nomeT;
       String ConteudoT;
       int CargHoraria = 0;
       String dataInT;
       String dataTerT;
       double ValTreinT = 0;
       int QtdParcT = 0; 
       String ObsT;       
       String msgErro = "";
       
       
       
       
       nomeT = txtNomeT.getText();
       
       ConteudoT = txtConteudoT.getText();
       
     
       
       dataInT = txtDataIninioT.getText();
       
       dataTerT = txtDataTerminoT.getText();
      
       
        
       ObsT = txtObsT.getText();
       
       String CargaHorariaAux = txtCargaHorariaT.getText();
       
       String QtdParcelasTAux = txtParcelasT.getText();
       
       String ValTreinamentoTAux = txtValTreinamento.getText();
       
       
       if (nomeT.equals("") && ConteudoT.equals("") && CargaHorariaAux.equals("")
                && dataInT.equals("") && dataTerT.equals("")
                && ValTreinamentoTAux.equals("") && QtdParcelasTAux.equals("")){
       
       msgErro = "TODOS OS CAMPOS DEVEM ESTAR PREENCHIDOS.";
            JOptionPane.showMessageDialog(null, msgErro);
        } else 
            if (nomeT.equals("")) {
                msgErro = "Preencha o campo EMPRESA antes de continuar.";
                JOptionPane.showMessageDialog(null, msgErro);
            } else 
              if (ConteudoT.equals("")) {
                    msgErro = "Preencha o campo CONTEUDO antes de continuar.";
                    JOptionPane.showMessageDialog(null, msgErro);
                } else {
                    if (CargaHorariaAux.equals("")) {
                    msgErro = "Preencha o campo CARGA HORARIA antes de continuar.";
                    JOptionPane.showMessageDialog(null, msgErro);
                } else {
                        if (dataInT.equals("")) {
                    msgErro = "Preencha o campo DATA INICIO antes de continuar.";
                    JOptionPane.showMessageDialog(null, msgErro);
                } else {
                     if (dataTerT.equals("")) {
                    msgErro = "Preencha o campo DATA TERMINO antes de continuar.";
                    JOptionPane.showMessageDialog(null, msgErro);
                } else {
                     if (ValTreinamentoTAux.equals("")) {
                    msgErro = "Preencha o campo VALOR TREINAMENTO antes de continuar.";
                    JOptionPane.showMessageDialog(null, msgErro);
                } else {
                         if (QtdParcelasTAux.equals("")) {
                    msgErro = "Preencha o campo QUANTIDADE DE PARCELAS antes de continuar.";
                    JOptionPane.showMessageDialog(null, msgErro);
                } else {
                        
                                    CargHoraria = Integer.parseInt(CargaHorariaAux);
                                    QtdParcT = Integer.parseInt(QtdParcelasTAux);
                                   // ValTreinT = Double.parseDouble(ValTreinamentoTAux);
                                      
                                    String ValTreina = ValTreinamentoTAux.replace(",", ".");                                     
            
                                    double valorTreina = Double.parseDouble(ValTreina); 
                             
                    



//aki        
        
    try {
        
        if (jTreinamento.getSelectedRow() != -1) {

            TurmaTreinamento turmatreinamento = new TurmaTreinamento();
            
            
            String valorAux = txtValTreinamento.getText();           
            
            String aux = valorAux.replace(",", ".");
            double valor = Double.parseDouble(aux); 
            
          
            
            turmatreinamento.setEmpresa(txtNomeT.getText());          
            turmatreinamento.setConteudo(txtConteudoT.getText());
            turmatreinamento.setCargaHoraria(Integer.parseInt(txtCargaHorariaT.getText())); 
            turmatreinamento.setDataInicio(txtDataInicioT.getText());
            turmatreinamento.setDataTermino(txtDataTerminoT.getText());
            turmatreinamento.setValorTreinamento(valor);
            turmatreinamento.setParcelas(Integer.parseInt(txtParcelasT.getText()));
            turmatreinamento.setObservacao(txtObsT.getText());        
                        
            turmatreinamento.setCod((int) jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 0));
            
          
         
         int resposta = JOptionPane.showConfirmDialog(null, "Deseja atualizar?", "Confirmação", JOptionPane.YES_NO_OPTION);
           
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    TreinamentoDAO.atualizar(turmatreinamento);
                    JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");
                } catch (SQLException ex) {
                    Logger.getLogger(TelaTurmaTreinamento.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TelaTurmaTreinamento.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (resposta == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Nada foi atualizado!");
                return;
            }
            
         
            readJTable();
                                        
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para atualizar.");  
        }
        
          } catch (Exception ex) {
           String msgErro1;
           msgErro1 = "Não é permitido campo nulo";
           JOptionPane.showMessageDialog(null, msgErro1);
       }
         }
                     }
                
                     }
                
                         
                    }
                
                    }
              }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTreinamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreinamentoMouseClicked
       
        if (jTreinamento.getSelectedRow() != -1) {
            
            NumberFormat nf = new DecimalFormat("#.#");

            txtNomeT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 1).toString());
            txtConteudoT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 2).toString());
            txtCargaHorariaT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 3).toString());
            txtDataInicioT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 4).toString());
            txtDataTerminoT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 5).toString());
            txtValTreinamento.setText(nf.format(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 6)));
            txtParcelasT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 7).toString());
            txtObsT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 8).toString());
            

        }
        
        
        
    }//GEN-LAST:event_jTreinamentoMouseClicked

    private void jTreinamentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreinamentoMouseReleased
    
    }//GEN-LAST:event_jTreinamentoMouseReleased

    private void jTreinamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTreinamentoKeyReleased
       
         if (jTreinamento.getSelectedRow() != -1) {
            
            NumberFormat nf = new DecimalFormat("#.#");

            txtNomeT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 1).toString());
            txtConteudoT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 2).toString());
            txtCargaHorariaT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 3).toString());
            txtDataInicioT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 4).toString());
            txtDataTerminoT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 5).toString());
            txtValTreinamento.setText(nf.format(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 6)));
            txtParcelasT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 7).toString());
            txtObsT.setText(jTreinamento.getValueAt(jTreinamento.getSelectedRow(), 8).toString());
            

        }
        
        
        
        
    }//GEN-LAST:event_jTreinamentoKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
     /*   try {                                        
            
            Connection con = ConexaoFactory.getConexao();  //conn = ConnectionFactory.getConnection();
            
            String src = "IREPORT/RelatorioDoTreinamento.jasper";
            
            JasperPrint jasperPrint = null;
            
            try {
                jasperPrint = JasperFillManager.fillReport(src, null, con);
            } catch (JRException ex) {
                System.out.println("Erro no Relatorio: " + ex);
            }
            
            JasperViewer view = new JasperViewer(jasperPrint, false);
            
            view.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaTurmaTreinamento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaTurmaTreinamento.class.getName()).log(Level.SEVERE, null, ex);
        }   */
     
     Connection con = ConnectionFactory.getConnection();
        String src = "IREPORT/RelatorioDoTreinamento.jasper";
        JasperPrint jasperPrint = null;
        try {
            jasperPrint = JasperFillManager.fillReport(src, null, con);
        } catch (JRException ex) {
            System.out.println("Error: " + ex);
        }
        JasperViewer view = new JasperViewer(jasperPrint, false);
        view.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTreinamento;
    private javax.swing.JTextField txtCargaHorariaT;
    private javax.swing.JTextField txtConteudoT;
    private javax.swing.JFormattedTextField txtDataInicioT;
    private javax.swing.JFormattedTextField txtDataIninioT;
    private javax.swing.JFormattedTextField txtDataTerminoT;
    private javax.swing.JTextField txtNomeT;
    private javax.swing.JTextField txtObsT;
    private javax.swing.JTextField txtParcelasT;
    private javax.swing.JFormattedTextField txtValTreinamento;
    // End of variables declaration//GEN-END:variables
}
