/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stecgames.visão;

import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import stecgames.persistencia.ConnectionFactory;


/**
 *
 * @author Sosciopata
 */
public class TelaPrincipal extends javax.swing.JFrame {

   
    public TelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
    public TelaPrincipal(String setor) {
        
        switch(setor){
            case "ADM":
                initComponents();
                setExtendedState(MAXIMIZED_BOTH);               
                break;
                
            case "RH":
                initComponents();
                setExtendedState(MAXIMIZED_BOTH);
                administrativoMenu.setEnabled(false);
                rhMenu.setEnabled(true);
                marketingMenu.setEnabled(false);
                almoxarifadoMenu.setEnabled(false);
                vendasMenu.setEnabled(false);
                cursosMenu.setEnabled(false);
                comprasMenu.setEnabled(false);
                mBackup.setEnabled(false);
                break; 
                
            case "MKG":
                initComponents();
                setExtendedState(MAXIMIZED_BOTH);
                administrativoMenu.setEnabled(false);
                rhMenu.setEnabled(false);
                marketingMenu.setEnabled(true);
                almoxarifadoMenu.setEnabled(false);
                vendasMenu.setEnabled(false);
                cursosMenu.setEnabled(false);
                comprasMenu.setEnabled(false);
                  mBackup.setEnabled(false);
                break; 
                
            case "ALM":
                initComponents();
                setExtendedState(MAXIMIZED_BOTH);
                administrativoMenu.setEnabled(false);
                rhMenu.setEnabled(false);
                marketingMenu.setEnabled(false);
                almoxarifadoMenu.setEnabled(true);
                vendasMenu.setEnabled(false);
                cursosMenu.setEnabled(false);
                comprasMenu.setEnabled(true);
                  mBackup.setEnabled(false);
                break;
                
            case "CUR":
                initComponents();
                setExtendedState(MAXIMIZED_BOTH);
                administrativoMenu.setEnabled(false);
                rhMenu.setEnabled(false);
                marketingMenu.setEnabled(false);
                almoxarifadoMenu.setEnabled(false);
                vendasMenu.setEnabled(false);
                cursosMenu.setEnabled(true);
                comprasMenu.setEnabled(false);
                  mBackup.setEnabled(false);
                break;
                
                case "VND":
                initComponents();
                setExtendedState(MAXIMIZED_BOTH);
                administrativoMenu.setEnabled(false);
                rhMenu.setEnabled(false);
                marketingMenu.setEnabled(false);
                almoxarifadoMenu.setEnabled(false);
                vendasMenu.setEnabled(true);
                cursosMenu.setEnabled(false);
                comprasMenu.setEnabled(false);
                  mBackup.setEnabled(false);
                break; 
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        administrativoMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        almoxarifadoMenu = new javax.swing.JMenu();
        LArmarios = new javax.swing.JMenuItem();
        LProdutos = new javax.swing.JMenuItem();
        LPedidos = new javax.swing.JMenuItem();
        LReq = new javax.swing.JMenuItem();
        comprasMenu = new javax.swing.JMenu();
        cursosMenu = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        marketingMenu = new javax.swing.JMenu();
        cadastrarCampanha = new javax.swing.JMenuItem();
        listarCampanha = new javax.swing.JMenuItem();
        rhMenu = new javax.swing.JMenu();
        jmCadastroFunc = new javax.swing.JMenuItem();
        jmMotivosOcorrencias = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        relPonto = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        vendasMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mBackup = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JdpPrincipal.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout JdpPrincipalLayout = new javax.swing.GroupLayout(JdpPrincipal);
        JdpPrincipal.setLayout(JdpPrincipalLayout);
        JdpPrincipalLayout.setHorizontalGroup(
            JdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        JdpPrincipalLayout.setVerticalGroup(
            JdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        jMenu.setText("Menu");

        jMenu2.setText("Setor");

        administrativoMenu.setText("Administrativo");

        jMenuItem2.setText("Cadastrar/Atualizar/Excluir usuarios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        administrativoMenu.add(jMenuItem2);

        jMenu6.setText("Relatórios");
        administrativoMenu.add(jMenu6);

        jMenu2.add(administrativoMenu);

        almoxarifadoMenu.setText("Almoxarifado");

        LArmarios.setText("Lista de Armários");
        LArmarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LArmariosActionPerformed(evt);
            }
        });
        almoxarifadoMenu.add(LArmarios);

        LProdutos.setText("Lista de Produtos");
        LProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LProdutosActionPerformed(evt);
            }
        });
        almoxarifadoMenu.add(LProdutos);

        LPedidos.setText("Lista de Pedidos");
        LPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LPedidosActionPerformed(evt);
            }
        });
        almoxarifadoMenu.add(LPedidos);

        LReq.setText("Lista Requisições");
        LReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LReqActionPerformed(evt);
            }
        });
        almoxarifadoMenu.add(LReq);

        jMenu2.add(almoxarifadoMenu);

        comprasMenu.setText("Compras");
        jMenu2.add(comprasMenu);

        cursosMenu.setText("Cursos e treinamentos");

        jMenuItem7.setText("Cadastro de Turmas do Curso");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        cursosMenu.add(jMenuItem7);

        jMenuItem8.setText("Cadastro de Turma  do Treinamento");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        cursosMenu.add(jMenuItem8);

        jMenuItem9.setText("Controle de Turmas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        cursosMenu.add(jMenuItem9);

        jMenuItem10.setText("Controle do Treinamento");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        cursosMenu.add(jMenuItem10);

        jMenu2.add(cursosMenu);

        marketingMenu.setText("Marketing");

        cadastrarCampanha.setText("Cadastrar Campanhas");
        cadastrarCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCampanhaActionPerformed(evt);
            }
        });
        marketingMenu.add(cadastrarCampanha);

        listarCampanha.setText("Listar Campanhas");
        listarCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarCampanhaActionPerformed(evt);
            }
        });
        marketingMenu.add(listarCampanha);

        jMenu2.add(marketingMenu);

        rhMenu.setText("RH");

        jmCadastroFunc.setText("Cadastro de Funcionario");
        jmCadastroFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroFuncActionPerformed(evt);
            }
        });
        rhMenu.add(jmCadastroFunc);

        jmMotivosOcorrencias.setText("Ocorrencias");
        jmMotivosOcorrencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMotivosOcorrenciasActionPerformed(evt);
            }
        });
        rhMenu.add(jmMotivosOcorrencias);

        jMenuItem5.setText("Registro de ponto");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        rhMenu.add(jMenuItem5);

        relPonto.setText("Relatorios de ponto");
        relPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relPontoActionPerformed(evt);
            }
        });
        rhMenu.add(relPonto);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Alterar/excluir ponto");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        rhMenu.add(jRadioButtonMenuItem1);

        jMenu2.add(rhMenu);

        vendasMenu.setText("Vendas");

        jMenuItem4.setText("Cadastro de Cliente Fisico");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        vendasMenu.add(jMenuItem4);

        jMenuItem11.setText("Cadastro de Cliente Jurídico");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        vendasMenu.add(jMenuItem11);

        jMenuItem13.setText("Cadastro de Jogos");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        vendasMenu.add(jMenuItem13);

        jMenuItem14.setText("Lista de Cliente Cadastrados/Iniciar Nova Venda");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        vendasMenu.add(jMenuItem14);

        jMenuItem15.setText("Listar Jogos");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        vendasMenu.add(jMenuItem15);

        jMenuItem12.setText("Gerar Relatório de Vendas");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        vendasMenu.add(jMenuItem12);

        jMenu2.add(vendasMenu);

        jMenu.add(jMenu2);

        jMenuItem3.setText("LogOff");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem3);

        jMenuBar1.add(jMenu);

        mBackup.setText("Backup");

        jMenuItem1.setText("Exportar banco de dados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mBackup.add(jMenuItem1);

        jMenuItem6.setText("Importar banco de dados");
        mBackup.add(jMenuItem6);

        jMenuBar1.add(mBackup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JdpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JdpPrincipal)
        );

        setSize(new java.awt.Dimension(816, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       //Executa o log off(desliga a a tela principal)
       // Trata confirmacao de logoff
        int opcao = JOptionPane.showConfirmDialog(this, 
                    "Deseja realmente fazer o Logoff?",
                    "Atenção", JOptionPane.YES_NO_OPTION);
        
        if(opcao == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(this, 
                    "Logoff cancelado");
            return;
        }
       new Logim().setVisible(true);
       jMenu.setEnabled(false);
       dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        CadastrarExcluirAlterarUsuarios altSenha = new  CadastrarExcluirAlterarUsuarios();
        JdpPrincipal.add(altSenha);
        altSenha.setLocation(
		JdpPrincipal.getWidth()/2 - altSenha.getWidth()/2,
		JdpPrincipal.getHeight()/2 - altSenha.getHeight()/2);
        altSenha.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
     BackupExportar  importarBd = new  BackupExportar();
     JdpPrincipal.add(importarBd);
     importarBd.setLocation(JdpPrincipal.getWidth()/2 - importarBd.getWidth()/2,
                            JdpPrincipal.getHeight()/2 - importarBd.getHeight()/2);
     importarBd.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void relPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relPontoActionPerformed
        // TODO add your handling code here:
        RelatorioPonto relatPonto = new RelatorioPonto();
        JdpPrincipal.add(relatPonto);
        relatPonto.setLocation(JdpPrincipal.getWidth()/2 - relatPonto.getWidth()/2,
            JdpPrincipal.getHeight()/2 - relatPonto.getHeight()/2);
        relatPonto.setVisible(true);
    }//GEN-LAST:event_relPontoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        RegistroDePonto tela = new RegistroDePonto();
        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jmMotivosOcorrenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMotivosOcorrenciasActionPerformed

        MotivosOcorrencia tela = new MotivosOcorrencia();
        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);
        tela.setVisible(true);

    }//GEN-LAST:event_jmMotivosOcorrenciasActionPerformed

    private void jmCadastroFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroFuncActionPerformed

        CadastroFunc tela = new CadastroFunc();
        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);
        tela.setVisible(true);

    }//GEN-LAST:event_jmCadastroFuncActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
        ExcluirAlterarPonto tela = new ExcluirAlterarPonto();
        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);
        
        tela.setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void LPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LPedidosActionPerformed
       telaListaPedido tela = new telaListaPedido();
          
        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);
          
       tela.setVisible(true);
    }//GEN-LAST:event_LPedidosActionPerformed

    private void LArmariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LArmariosActionPerformed
        telaListaArmario tela = new telaListaArmario();
        
        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);
        
        
        tela.setVisible(true);
    }//GEN-LAST:event_LArmariosActionPerformed

    private void LProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LProdutosActionPerformed
        telaListaProduto tela = new telaListaProduto();
        
        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);
        
        tela.setVisible(true);
    }//GEN-LAST:event_LProdutosActionPerformed

    private void LReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LReqActionPerformed
         telaListaRequisicoes tela;
        try {
            tela = new telaListaRequisicoes(); JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);
         
         
        tela.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
         
       
    }//GEN-LAST:event_LReqActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        TelaCurso tela = new TelaCurso();

        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);

        tela.setVisible(true);
        

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        
        TelaTreinamento tela = new TelaTreinamento();

        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);

        tela.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        TelaTurmaCurso tela = new TelaTurmaCurso();

        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);

        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        TelaTurmaTreinamento tela = new TelaTurmaTreinamento();

        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);

        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void listarCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarCampanhaActionPerformed

          ListarCampanhas tela = new ListarCampanhas();

        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);

        tela.setVisible(true);
    }//GEN-LAST:event_listarCampanhaActionPerformed

    private void cadastrarCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCampanhaActionPerformed
    
         CadastroCampanhas tela = new CadastroCampanhas();

        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);

        tela.setVisible(true);
        
    }//GEN-LAST:event_cadastrarCampanhaActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ClienteFisicoTela tela = new ClienteFisicoTela();

        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);

        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        Connection conn = ConnectionFactory.getConnection();
        
        String src = "Vendas.jasper";
        
        JasperPrint jasperPrint = null;
        try {
            jasperPrint = JasperFillManager.fillReport(src, null, conn);
             } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
        
        JasperViewer view = new JasperViewer(jasperPrint, false);
        
        view.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        ClienteJuridicoT tela = new ClienteJuridicoT();

        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);

        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        CadastroJogosTela tela = new CadastroJogosTela();

        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);

        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        ListarClientesTela tela = new ListarClientesTela();

        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);

        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        ListarJogos tela = new ListarJogos();

        JdpPrincipal.add(tela);
        tela.setLocation(
            JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
            JdpPrincipal.getHeight()/2 - tela.getHeight()/2);

        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try{
            UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
        }catch (Exception e){
            
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane JdpPrincipal;
    private javax.swing.JMenuItem LArmarios;
    private javax.swing.JMenuItem LPedidos;
    private javax.swing.JMenuItem LProdutos;
    private javax.swing.JMenuItem LReq;
    private javax.swing.JMenu administrativoMenu;
    private javax.swing.JMenu almoxarifadoMenu;
    private javax.swing.JMenuItem cadastrarCampanha;
    private javax.swing.JMenu comprasMenu;
    private javax.swing.JMenu cursosMenu;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuItem jmCadastroFunc;
    private javax.swing.JMenuItem jmMotivosOcorrencias;
    private javax.swing.JMenuItem listarCampanha;
    private javax.swing.JMenu mBackup;
    private javax.swing.JMenu marketingMenu;
    private javax.swing.JMenuItem relPonto;
    private javax.swing.JMenu rhMenu;
    private javax.swing.JMenu vendasMenu;
    // End of variables declaration//GEN-END:variables
}
