/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stecgames.visão;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import stecgames.modelo.TurmaCurso;
import stecgames.persistencia.CursoDAO;
import stecgames.utilitarios.ApenasNumerosVirg;
import stecgames.utilitarios.ApenasNumeros;
import static stecgames.visão.TelaPrincipal.JdpPrincipal;

/**
 *
 * @author Gustavo
 */
public class TelaCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCurso
     */
    public TelaCurso() {
        initComponents();
        
        
        
        txtIdadeMinC.setDocument(new ApenasNumeros());
        txtIdadeMaxC.setDocument(new ApenasNumeros());
        txtValMatrC.setDocument(new ApenasNumerosVirg());
        txtValMensC.setDocument(new ApenasNumerosVirg());
        txtQtdParcelasC.setDocument(new ApenasNumeros());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdadeMinC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdadeMaxC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtValMatrC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtValMensC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQtdParcelasC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObsC = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbPeriodoC = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Cadastro de Curso");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cadastro de Curso");

        jLabel3.setText("Nome:");

        txtNomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCActionPerformed(evt);
            }
        });

        jLabel4.setText("Idade Mínima:");

        txtIdadeMinC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeMinCActionPerformed(evt);
            }
        });

        jLabel5.setText("Idade Máxima:");

        txtIdadeMaxC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeMaxCActionPerformed(evt);
            }
        });

        jLabel6.setText("Período:");

        jLabel7.setText("Valor da Matrícula:");

        txtValMatrC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValMatrCActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor da Mensalidade:");

        jLabel9.setText("Parcelas:");

        jLabel11.setText("obs:");

        txtObsC.setColumns(20);
        txtObsC.setRows(5);
        jScrollPane1.setViewportView(txtObsC);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cbPeriodoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Matutino", "Vespertino", "Noturno" }));
        cbPeriodoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPeriodoCActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdadeMinC, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(txtNomeC)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValMatrC, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(45, 45, 45)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtIdadeMaxC, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbPeriodoC, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtQtdParcelasC)
                                        .addComponent(txtValMensC))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel2)))
                        .addContainerGap(71, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(43, 43, 43)
                                .addComponent(jButton2)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 20, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIdadeMinC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdadeMaxC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbPeriodoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtValMatrC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtValMensC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtQtdParcelasC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCActionPerformed

    private void txtIdadeMinCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeMinCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeMinCActionPerformed

    private void txtIdadeMaxCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeMaxCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeMaxCActionPerformed

    private void txtValMatrCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValMatrCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValMatrCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
         dispose();   
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
       
        String nomeC;
        int IdadeMinC = 0;
        int IdadeMaxC = 0;            
        double ValMatrC = 0;
        double ValMensC = 0;
        int QtdParcelasC = 0;        
        String ObsC;
        String msgErro = "";
       
        
       
       
       nomeC = txtNomeC.getText();   
              
       //String PeriodoC = cbPeriodoC.getSelectedItem().toString();                 
        
       String IdadeMiCAux = txtIdadeMinC.getText();
       
       String IdadeMaCAux = txtIdadeMaxC.getText();
       
       String Periodo = cbPeriodoC.getSelectedItem().toString();      
        
       String ValMatCAux = txtValMatrC.getText();
       
       String ValMenSCAux = txtValMensC.getText();
       
       String QtdParcCAux = txtQtdParcelasC.getText();
       
       ObsC = txtObsC.getText();
       
       
       
       try {
       
       if (nomeC.equals("") && Periodo.equals("") && IdadeMiCAux.equals("")
                && IdadeMaCAux.equals("") && ValMatCAux.equals("")
                && ValMenSCAux.equals("") && QtdParcCAux.equals("")){
           
           
            msgErro = "TODOS OS CAMPOS DEVEM ESTAR PREENCHIDOS.";
            JOptionPane.showMessageDialog(null, msgErro);
        } else {
            if (nomeC.equals("") || nomeC.equals(null)) {
                msgErro = "Preencha o campo NOME antes de continuar.";
                JOptionPane.showMessageDialog(null, msgErro);
            } else {
                if (IdadeMiCAux.equals("")) {
                    msgErro = "Preencha o campo Idade Minima antes de continuar.";
                    JOptionPane.showMessageDialog(null, msgErro);
                } else {
                    if (IdadeMaCAux.equals("")) {
                        msgErro = "Preencha o campo Idade Maxima antes de continuar.";
                        JOptionPane.showMessageDialog(null, msgErro);
                    } else {
                        if(Periodo.equals("Selecione")){
                          msgErro = "Selecione um Periodo antes de continuar.";
                           JOptionPane.showMessageDialog(null, msgErro);
                         }else{
                        if (ValMatCAux.equals("")) {
                            msgErro = "Preencha o campo Valor Matricula antes de continuar.";
                            JOptionPane.showMessageDialog(null, msgErro);
                        } else {
                            if (ValMenSCAux.equals("")) {
                                msgErro = "Preencha o campo Valor da Mensalidade antes de continuar.";
                                JOptionPane.showMessageDialog(null, msgErro);
                            } else {
                                if (QtdParcCAux.equals("")) {
                                    msgErro = "Preencha o campo Quantidade de Parcelas antes de continuar.";
                                    JOptionPane.showMessageDialog(null, msgErro);
                                } else {
                                    
                                   
                                    
                                    
                                      
                                          
                                    IdadeMinC = Integer.parseInt(IdadeMiCAux);
                                    IdadeMaxC = Integer.parseInt(IdadeMaCAux);                                    
                                   // ValMatrC = Double.parseDouble(ValMatCAux);
                                    //ValMensC = Double.parseDouble(ValMenSCAux);
                                    QtdParcelasC = Integer.parseInt(QtdParcCAux);
                                    
                                    
                                     String Mat = ValMatCAux.replace(",", ".");                                     
            
                                     double valorMat = Double.parseDouble(Mat);
                                     
                                     String Mens = ValMenSCAux.replace(",", ".");                                     
            
                                     double valorMens = Double.parseDouble(Mens);
                                     
                                     
                                    
                                    

                                    if (nomeC != null) {

                                        TurmaCurso turmacurso = new TurmaCurso();
                                        turmacurso.setNome(nomeC);
                                        turmacurso.setIdadeMin(IdadeMinC);
                                        turmacurso.setIdadeMax(IdadeMaxC);
                                        turmacurso.setPeriodo(Periodo);
                                        turmacurso.setValorMat(valorMat);
                                        turmacurso.setValorMens(valorMens);
                                        turmacurso.setQtdParcelas(QtdParcelasC);
                                        turmacurso.setObservacao(ObsC);
                                        
                                        
                                        
                                         int resposta = JOptionPane.showConfirmDialog(null, nomeC + " Cadastrado com sucesso! Deseja cadastrar outro?",  "Confirmação", JOptionPane.YES_NO_OPTION);
                                         
                                       if (resposta == JOptionPane.YES_OPTION) {
                                           
                                           CursoDAO.inserir(turmacurso);
                                           
                                           txtNomeC.setText("");
                                           txtIdadeMinC.setText("");
                                           txtIdadeMaxC.setText("");
                                           cbPeriodoC.setSelectedItem("Selecione");
                                           txtValMatrC.setText("");
                                           txtValMensC.setText("");
                                           txtQtdParcelasC.setText("");   
                                           txtObsC.setText("");
                                           
                                           return;
                                       }
                                        
                                         
                                         if (resposta == JOptionPane.YES_OPTION) {
                                        try {   
                                             
                                            CursoDAO.inserir(turmacurso);
                                          
                                          
                                           txtNomeC.setText("");
                                           txtIdadeMinC.setText("");
                                           txtIdadeMaxC.setText("");
                                           cbPeriodoC.setSelectedItem("Selecione");
                                           txtValMatrC.setText("");
                                           txtValMensC.setText("");
                                           txtQtdParcelasC.setText("");   
                                           txtObsC.setText("");
                                          return;
                                           
                                        } catch (SQLException ex) {
                                           Logger.getLogger(TelaTurmaCurso.class.getName()).log(Level.SEVERE, null, ex);
                                         } catch (ClassNotFoundException ex) {
                                            Logger.getLogger(TelaTurmaCurso.class.getName()).log(Level.SEVERE, null, ex);
                                       }
                                      } else if (resposta == JOptionPane.NO_OPTION) {
                                          
                                          CursoDAO.inserir(turmacurso);
                                          
                                         TelaTurmaCurso tela = new TelaTurmaCurso();
                                               
                                                 JdpPrincipal.add(tela);
                                                 tela.setLocation(
                                                 JdpPrincipal.getWidth()/2 - tela.getWidth()/2,
                                                 JdpPrincipal.getHeight()/2 - tela.getHeight()/2);
                                                  tela.setVisible(true);
                                         }
                                        
                                      
                    }
                }
            }
        }
       
       }
        
    }                                           

   }
      
   }
   }     
       } catch (Exception ex) {
           String msgErro1;
           msgErro1 = "Insira apenas uma virgula";
           JOptionPane.showMessageDialog(null, msgErro1);
       }
       
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbPeriodoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPeriodoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPeriodoCActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
    txtNomeC.setText("");
    txtIdadeMinC.setText("");
    txtIdadeMaxC.setText("");
    cbPeriodoC.setSelectedItem("Selecione");
    txtValMatrC.setText("");
    txtValMensC.setText("");
    txtQtdParcelasC.setText("");   
    txtObsC.setText("");
    
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbPeriodoC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdadeMaxC;
    private javax.swing.JTextField txtIdadeMinC;
    private javax.swing.JTextField txtNomeC;
    private javax.swing.JTextArea txtObsC;
    private javax.swing.JTextField txtQtdParcelasC;
    private javax.swing.JTextField txtValMatrC;
    private javax.swing.JTextField txtValMensC;
    // End of variables declaration//GEN-END:variables
}
